---
# tasks file for kibana-role
- name: Install kibana
  get_url:
      url: "https://artifacts.elastic.co/downloads/kibana/kibana-7.15.0-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-7.15.0-linux-x86_64.tar.gz"
      mode: 0755
      timeout: 60
      force: true
    register: get_kibana
    until: get_kibana is succeeded
    tags: kibana
  - name: Create directrory for Kibana
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: kibana
  - name: Extract kibava in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-7.15.0-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/kibana"
    tags:
      - skip_ansible_lint
      - kibana
